config/routes.rb
Rails.application.routes.draw do


  resources :follows
  resources :group_reviews
  resources :select_reviews
  resources :review_homes
  resources :store_comments
  resources :goods_comments
  resources :categories
  resources :messages
  resources :select_categories
  get 'chats/index'
  get 'users/profile'
  root to: 'chats#index'
  resources :groups
  resources :chats
  resources :occupations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'profile'
  delete '/users/:id', to: 'users#destroy', as: 'unsubscribe'
  get '/image_of_users/:id',to: 'users#send_image',as: 'image_of_users'
  get '/image_of_categories/:id', to: 'categories#send_image', as: 'image_of_categories'
  get '/image_of_goods_reviews/:id', to: 'goods_reviews#send_image', as: 'image_of_goods_reviews'
  get '/image_of_store_reviews/:id', to: 'store_reviews#send_image', as: 'image_of_store_reviews'

  delete 'followed_user/:id', to: 'follows#destroy', as: 'followunsubscribe'

  get'/image_of_groups/:id',to: 'groups#send_image', as: 'image_of_groups'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  
  resources :users
  resources :chats
  resources :store_reviews
  resources :store_comments
  resources :goods_reviews
end
  

app/controllers/goods_reviews_controller.rb
class GoodsReviewsController < ApplicationController
  before_action :set_goods_review, only: %i[ show edit update destroy ]

  # GET /goods_reviews or /goods_reviews.json
  def index
    @goods_reviews = GoodsReview.all
  end

  # GET /goods_reviews/1 or /goods_reviews/1.json
  def show
  end

  # GET /goods_reviews/new
  def new
    @goods_review = GoodsReview.new
  end

  # GET /goods_reviews/1/edit
  def edit
  end

  # POST /goods_reviews or /goods_reviews.json
  def create
    @goods_review = GoodsReview.new(goods_review_attributes)
    @goods_review.user_id = current_user.id
    @goods_review.group_id = session["selected_group_id_#{current_user.id}"]
    # group = Group.find(session["selected_group_id_#{current_user.id}"])

    # @store_review.user_id = current_user.id

    respond_to do |format|
      if @goods_review.save
        format.html { redirect_to goods_review_url(@goods_review), notice: "Goods review was successfully created." }
        format.json { render :show, status: :created, location: @goods_review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @goods_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goods_reviews/1 or /goods_reviews/1.json
  def update
    respond_to do |format|
      if @goods_review.update(goods_review_attributes)
        format.html { redirect_to goods_review_url(@goods_review), notice: "Goods review was successfully updated." }
        format.json { render :show, status: :ok, location: @goods_review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @goods_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods_reviews/1 or /goods_reviews/1.json
  def destroy
    @goods_review.destroy

    respond_to do |format|
      format.html { redirect_to goods_reviews_url, status: :see_other, notice: "Goods review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def send_image
    goods_review = GoodsReview.find(params[:id])
    send_data(goods_review.review_image, disposition: :inline)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goods_review
      @goods_review = GoodsReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def goods_review_params
      params.require(:goods_review).permit(:title, :review_image, :review, :evaluation, :price, :category_id)
    end

    def goods_review_attributes
      if goods_review_params[:review_image].nil?
        {
          title: goods_review_params[:title], review: goods_review_params[:review], evaluation: goods_review_params[:evaluation].to_i, price: goods_review_params[:price], category_id: goods_review_params[:category_id]
        }
      else
      {
        title: goods_review_params[:title], review_image: goods_review_params[:review_image].read, review: goods_review_params[:review], evaluation: goods_review_params[:evaluation].to_i, price: goods_review_params[:price], category_id: goods_review_params[:category_id]
      }
      end
    end
    
end

app/helpers/goods_reviews_helper.rb
module GoodsReviewsHelper
end

app/views/goods_reviews/_form.html.erb
<%= form_with(model: goods_review) do |form| %>
  <% if goods_review.errors.any? %>
  
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(goods_review.errors.count, "error") %> prohibited this goods_review from being saved:</h4>

      <ul>
        <% goods_review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h2 class="text-center">レビュー作成</h2>

  <div class="form-group ">
    <%= form.label :title, "商品名（必須）", class: "form-label" %>
    <%= form.text_field :title, placeholder: "商品の名前を入力してください", class: "form-control" %>
  </div>

  <div class="row">
        
        <div class="col-md-8 border text-center">
           
            <div id="img"></div>
            <script>
                function preview(obj) {
                
                // 選択した全てのファイルに対してループ処理をします。
                for (i = 0; i < obj.files.length; i++) {
                    // FileReaderオブジェクトを作成します。これによりブラウザ上でファイルを読み込むことが可能になります。
                    let fileReader = new FileReader();
                    // onloadイベントハンドラを設定します。ファイルが正常に読み込まれたときに呼び出されます。
                    fileReader.onload = ((e)=> {
                        // 読み込んだ画像ファイルをData URLとしてimg要素に設定します。
                        // これにより、選択した画像がブラウザ上でプレビュー表示されます。
                        document.querySelector('#img').innerHTML = '<img src="' + e.target.result + '"  width="100" height="100" >';
                      <% if goods_review.review_image.nil? %>
                        kamera = document.getElementById("kamera");
                        kamera.style.display = 'none';
                      <% else %>
                        aikon = document.getElementById("aikon");
                        aikon.style.display = 'none';
                      <% end %>
                    });
                    // ファイルをData URLとして読み込みます。
                    fileReader.readAsDataURL(obj.files[i]);
                    }
                }
            </script>
            
            <%= form.label :review_image , "アイコンを選択", class: "btn btn--form" %>
            
             <%if goods_review.id.nil? or goods_review.review_image.nil?%>
              
            
              <div class = "col-md-6">
                 <%= image_tag '/images/railskame.jpg',size:'150x110',id:"kamera" %>
              </div> 
              <%= form.file_field :review_image , :size=>"40", class: "form_file" ,onchange:"preview(this);" %>
            <%else%> 
              <%= image_tag(url_for(image_of_goods_reviews_path(@goods_review.id)),size: '100x100',id:"aikon") %>
              <%= form.file_field :review_image , :size=>"40", class: "form_file" ,onchange:"preview(this);" %>
            <%end%>

        </div>
    </div>

  <div class="form-group mb-3">
    <%= form.label :review, "レビュー本文（必須）", class: "form-label" %>
    <%= form.text_area :review, placeholder: "レビューを入力してください", class: "form-control", rows: 5 %>
  </div>

  <div class="form-group mb-3">
        <%= form.label :price, "価格（必須）", class: "form-label" %>
<%= form.text_field :price, placeholder: "価格を入力してください", class: "form-control" %>
    </div>  
      
  
  <div class="form-group mb-3">
    <%= form.label :category_id, "カテゴリー（必須）", class: "form-label" %>
    <%= form.select :category_id, Category.all.map { |category| [category.name, category.id] }, { prompt: "商品のカテゴリーを入力してください" }, class: "form-select" %>
  </div>

  <%# <div class="field">
    <%= form.label :user_id %>
    <%# <%= form.number_field :user_id %>
  <%# </div> %>

  <%# <div class="field">
    <%= form.label :group_id %>
    <%# <%= form.number_field :group_id %>
  <%# </div>  %>

  <%# <div>
    <%= session["selected_group_id_#{current_user.id}"]%>
  <%# </div> %>

<div class="form-group mb-3">
    <%= form.label :evaluation, "評価（必須）", class: "form-label" %>
    <div class="star-rating">
      <%= form.select :evaluation, [["★☆☆☆☆", 1], ["★★☆☆☆", 2], ["★★★☆☆", 3], ["★★★★☆", 4], ["★★★★★", 5]], {}, class: "form-select" %>
    </div>
  </div>

  <div class="text-center">
    <%= form.submit "投稿", class: "btn btn-primary px-5" %>
  </div>
</div>

<% end %>
<style>
h2{
  font-size: 40px;
}
</style>

app/views/goods_reviews/edit.html.erb
<h1>商品レビュー編集</h1>

<%= render 'form', goods_review: @goods_review %>

<%= link_to 'Show', @goods_review %> |

app/views/goods_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<div style="text-align: center;">
 <div class="fixed-top">
      <div class=row>
        <div class=col-md-1></div>
        <div class=col-md-1>
          
             <h1>
             <%= link_to "＜", chats_path, class: "back-button", style: "margin-right: 10px;" "font-size: 30px;" %>
                
        </div>
        <div class=col-md-2></div>
      </div>
  </div>
</div>
<h1>商品レビュー</h1>

<div class="container mt-4">
  <div class="row">
    <% @goods_reviews.each do |goods_review| %>
      <div class="col-md-4">
        <a href="<%= goods_review_path(goods_review) %>" class="text-decoration-none">
          <div class="card mb-4" style="cursor: pointer;">
            <%= image_tag(url_for(image_of_goods_reviews_path(goods_review)), class: "card-img-top custom-image", style: "width: 100%; height: 80px; object-fit: contain;") %>
            <div class="card-body">
              <h5 class="card-title text-dark"><%= goods_review.title %></h5>
              <%# <p class="card-text text-muted"> %>
                <%# <%= truncate(goods_review.review, length: 200) %>
              <%# </p> %>
            </div>
              <div class="card-footer text-muted">
                <%= time_ago_in_words(goods_review.created_at) %> 前
              </div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</div>

<br><br>

<%= link_to '商品レビュー投稿', new_goods_review_path, class: "btn btn-light" %>

<style>
  .card {
    height: 200px;
  }

  .custom-image {
    width: 100%;
    height: 100px;
    object-fit: cover;
  }

  .card-title {
    font-size: 1.25rem;
  }

  .card-text {
    font-size: 0.9rem;
  }

  .card:hover {
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    transform: scale(1.02);
    transition: 0.3s;
  }
</style>

app/views/goods_reviews/new.html.erb
<div style="display: flex; align-items: center;">
      <%= link_to "＜", :back, class: "back-button", style: "margin-right: 10px; font-size: 30px;" %>
    </div>

<%= render 'form', goods_review: @goods_review %>

app/views/goods_reviews/show.html.erb
<p id="notice"><%= notice %></p>
<div style="display: flex; align-items: center;">
  <%= link_to "＜", :back, class: "back-button", style: "margin-right: 10px;" "font-size: 30px;" %>
</div>
<h1>
  <%= @goods_review.title %>
</h1>

<p>
<div class="image-container">
  <%= image_tag(url_for(image_of_goods_reviews_path(@goods_review)), class: "img-fluid") %>
</div>


</p>

<h2>
  <strong>レビュー:</strong>
  <%= @goods_review.review %>
</h2>

<h2>
  <strong>価格:</strong>
  <%= @goods_review.price %><%= '円' %>
</h2>

<h3>
  <strong>評価:</strong>
  <%= @goods_review.evaluation %>
</h3>

<% if current_user == @user %>
<div style="text-align: right;">
  <%= link_to 'Edit', edit_goods_review_path(@goods_review) %>
</div>
<% end %>




<h4>コメント</h4>
<%= form_tag("/goods_comments") do %>
  <%= hidden_field :goods_comment, :goods_review_id, value: @goods_review.id %>
  <%= text_area :goods_comment, :comment, class: 'form-control', id: 'floatingTextarea2', style: 'height:50px' %>
  <div style="text-align: right;">
    <%= submit_tag "コメント追加" %>
  </div>
<% end %>

<% @goods_review.goods_comments.each do |goods_comment| %>
  <%= link_to image_tag(url_for(image_of_users_path(goods_comment.user_id)),size:'50x50'),users_profile_path(user_id: goods_comment.user_id) %>
  <p><%= goods_comment.user.name %><br><%= goods_comment.created_at.strftime('%Y年%m月%d日%t %H時%M分%S秒') %></P>
  <p><%= goods_comment.comment %></P>
<% end %>

<style>
  h1{
    text-align: center;
  }
  h2{
    font-size: 20px;
  }
  h3{
    font-size: 35px;
  }
  .image-container {
  max-width: 300px; /* 必要な幅に制限 */
  margin: 0 auto;   /* センター配置（オプション） */
}

</style>