config/routes.rb
Rails.application.routes.draw do


  resources :follows
  resources :group_reviews
  resources :select_reviews
  resources :review_homes
  resources :store_comments
  resources :goods_comments
  resources :categories
  resources :messages
  resources :select_categories
  get 'chats/index'
  get 'users/profile'
  root to: 'chats#index'
  resources :groups
  resources :chats
  resources :occupations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'profile'
  delete '/users/:id', to: 'users#destroy', as: 'unsubscribe'
  get '/image_of_users/:id',to: 'users#send_image',as: 'image_of_users'
  get '/image_of_categories/:id', to: 'categories#send_image', as: 'image_of_categories'
  get '/image_of_goods_reviews/:id', to: 'goods_reviews#send_image', as: 'image_of_goods_reviews'
  get '/image_of_store_reviews/:id', to: 'store_reviews#send_image', as: 'image_of_store_reviews'

  delete 'followed_user/:id', to: 'follows#destroy', as: 'followunsubscribe'

  get'/image_of_groups/:id',to: 'groups#send_image', as: 'image_of_groups'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  
  resources :users
  resources :chats
  resources :store_reviews
  resources :store_comments
  resources :goods_reviews
end
  

app/models/group.rb
class Group < ApplicationRecord
has_many :chats, dependent: :destroy 
has_many :store_reviews, dependent: :destroy
has_many :goods_reviews, dependent: :destroy 
has_many :messages, dependent: :destroy
belongs_to :category,optional: false 
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    if params[:search].present? && params[:search][:keyword].present?
      @groups = Group.where("name like '%#{params[:search][:keyword]}%'").order(created_at: :desc)
    else
      @groups = Group.all.order(created_at: :desc)
    end
    if params[:selectedcategory].present? 
      @groups = @groups.where("category_id=?",params[:selectedcategory]).order(created_at: :desc)
    end

    @select_categories = SelectCategory.where(user_id: current_user.id)
    session["selected_group_id_#{current_user.id}"] = params[:group_id]
    
  end

  # def search
  #   @groups = Group.all
  # end

  # GET /groups/1 or /groups/1.json
  # def show
  # end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_attributes)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_attributes)
        format.html { redirect_to @group, notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_path, status: :see_other, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def show
    @group = Group.find(params[:id])
    @chat = Chat.find_by(group_id:params[:id])
    if @chat.nil?
      @chat = Chat.new
    end
    session["selected_group_id_#{current_user.id}"] = params[:id]
  end

  def send_image
    group = Group.find(params[:id])
    send_data(group.group_image,disposition: :inline)
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :group_image, :introduction, :category_id)
    end
    def group_attributes
      {
        name: group_params[:name],group_image: group_params[:group_image].read,introduction:group_params[:introduction],category_id:group_params[:category_id]
      }
    end

end

app/helpers/groups_helper.rb
module GroupsHelper
  def home
    if (controller.controller_name == "chats" and controller.action_name == "show") or (controller.controller_name == "messages" and controller.action_name == "index")
      @grouplist = Chat.all
      true
    else
      false
    end
  end

end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


        
        <div class="form-group mb-3">
          <%= form.label :name, class: "form-label" %>
          <%= form.text_field :name, placeholder: "グループの名前を入力してください", class: "form-control" %>
        </div>
        
        <div class="mb-3">
          <div id="img" class="text-center">
            <%= form.label :group_image, "アイコンを選択", class: "btn btn-outline-primary" %>
            <% if group.group_image.nil? %>
              <div class="mb-3">
                <%= image_tag '/images/railskame.jpg', size: '150x110', id: "kamera" %>
              </div>
              <%= form.file_field :group_image, class: "form-control", onchange: "preview(this);" %>
            <% else %>
              <div class="mb-3">
                <%= image_tag(url_for(image_of_groups_path(@group)), size: '100x100', id: "aikon") %>
              </div>
              <%= form.file_field :group_image, class: "form-control", onchange: "preview(this);" %>
            <% end %>
          </div>
        </div>
        
        <div class="field mb-3">
          <%= form.label :introduction, '紹介文', class: "form-label" %>
          <%= form.text_area :introduction, class: "form-control", style: "height:150px;" %>
        </div>
        
        <div class="field mb-3">
          <%= form.label :category_id, class: "form-label" %>
          <%= form.select :category_id, Category.all.map { |category| [category.name, category.id] }, {}, class: "form-select" %>
        </div>

<div class="actions text-center">
  <%= form.submit '保存', class: "btn btn-primary btn-block" %>
</div>


      </div>
      
    </div>

  <script>
    function preview(obj) {
      for (i = 0; i < obj.files.length; i++) {
        let fileReader = new FileReader();
        fileReader.onload = (e) => {
          document.querySelector('#img').innerHTML = '<img src="' + e.target.result + '" width="200" height="200" class="rounded-circle border">';
        };
        fileReader.readAsDataURL(obj.files[i]);
      }
    }
  </script>

<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>
<div style="display: flex; align-items: center;">
  <%= link_to "＜", chats_path, class: "back-button", style: "margin-right: 10px;" "font-size: 30px;" %>
  <h1>グループ参加</h1>
</div>

    <%= form_tag(groups_path,method: :get) do %>
      
      <%= text_field_tag "search[keyword]",nil,placeholder: "🔍 検索",class: "form-control" %>
    <% end %>
    
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
<script src="https://cdn.jsdelivr.net/npm//swiper@11/swiper-bundle.min.js"></script>

<div class="swiper-container">
<div class="swiper">
  <div class="swiper-wrapper">
    <% @select_categories.each do |category| %>
      <div class="swiper-slide">        
        <%= link_to image_tag(url_for(image_of_categories_path(category.category_id)),size:'100x100'), groups_path(selectedcategory:category.category_id) %>
        <%# image_tag(url_for(image_of_categories_path(category.category_id)),size: "100x100")%></div> 
    <% end %>
    </div>
  </div>
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>
  </div>

  <script>
  const swiper = new Swiper('.swiper',{
    direction: 'horizontal',
    loop: true,
    centeredSlides: true,
    slidesPerView:4.8,
    spaceBetween: 30,
    navigation:{
      nextEl:'.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },
  });
  </script>

  <style>
  .swiper-container{
    margin-inline:auto;
    width: auto;
    position: relative;
  }
  .swiper {
    max-width: 80%
  }
  /*前への矢印*/
  .swiper-button-prev{
    left: -30px;
  }
  /*次への矢印*/
  swiper-button-next{
    right: -30px;
  }
  </style>
   
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to image_tag(url_for(image_of_groups_path(group)),size:'70x70'), group %></td> 
        <td><%= link_to group.name,group %></td>
        <td><%= group.introduction %></td>
        
        <%# <td><%= link_to 'Edit', edit_group_path(group) %><%# </td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %><%# </td>
        <td><%= link_to 'Show', group %><%# </td>%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to '新しいグループを作成', new_group_path, class: 'right-align' %>

<style>
.right-align {
  float: right;
  display: inline-block;
  border: solid 2px;
}

<%= link_to '新しいグループを作成', new_group_path %>
</style>

app/views/groups/new.html.erb
<div style="display: flex; align-items: center;">
      <%= link_to "＜", :back, class: "back-button", style: "margin-right: 10px; font-size: 30px;" %>
    </div><h2>グループ作成</h2>

<%= render 'form', group: @group %>


    <style>
        h2 {
            text-align: center;
            font-size: 35px;
        }
    </style>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>
        <div class=col-md-6>
          
             <h1>
             <%= link_to "＜", chats_path, class: "back-button", style: "margin-right: 10px;" "font-size: 30px;" %>
                
        </div>
<div style="text-align: center;">
 <div class="fixed-top">
      <div class=row>
        <div class=col-md-1></div>

        <div class=col-md-2></div>
      </div>
   </div>
<p>
  <%= image_tag(url_for(image_of_groups_path(@group)),size: '200x200') %>
</p>

<p style="font-size: 30px;">
  <%= @group.name %>
</p>



<p style="font-size: 22px;">
  <%= @group.introduction %>
</p>

<p style="font-size: 20px;">
  <strong>カテゴリー:</strong>
  <%= @group.category.name %>
</p>

<% if @group.chats.blank? %>
  <%= form_with(model: @chat) do |form| %>
    <%= form.hidden_field :group_id, value: @group.id %>
    <%= form.submit %>
  <% end %>
<% end %>
<div class="container">
  <div class="row text-center">
    <div class="col">
      <%= link_to messages_path(chat_id: @chat.id) do %>
        <%= image_tag '/images/chat.jpg', size: '70x70' %>
      <% end %>
      <br>
      <strong>Chat</strong>
    </div>
    <div class="col">
      <%= link_to group_reviews_path(group_id:@group.id) do %>
        <%= image_tag '/images/review.jpg', size: '70x70' %>
      <% end %>
      <br>
      <strong>Review</strong>
    </div>
  </div>
</div>




</div>
<br>

<div style="text-align: right;">
</div>